#!/bin/sh

VERS=14.2.0

LIBS=

unamem=`uname -m`

if [ $unamem = x86_64 ]; then
ARCH=x86_64
LIBS=
if [ -d /usr/lib/x86_64-linux-gnu ]; then
export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
fi
else
ARCH=i386
if [ -d /usr/lib/i386-linux-gnu/ ]; then
export LIBRARY_PATH=/usr/lib/i386-linux-gnu/
fi
fi

CFLAGS=
CPPFLAGS=
CC=
rm -rf gcc-${VERS}
xzcat /tmp/gcc-${VERS}.tar.xz|tar xpf -
#tar xzf patch/gcc-vmscall-0_3_11.tar.gz
#patch -p1 < gcc-vmscall/gcc-4.2.1-vmscall.patch
#tar xzf tmp/gcc-testsuite-4.2.1.tar.gz
rm bliss
ln -sf gcc-${VERS} bliss
rsync -a gcc/ gcc-${VERS}/gcc
rm -rf build
mkdir build
cd build
if [ $unamem = x86_64 ]; then
../gcc-${VERS}/configure --enable-languages=bliss --with-included-gettext  --prefix=`pwd`/../usr --disable-multilib 
else
../gcc-${VERS}/configure --enable-languages=bliss --with-included-gettext --prefix=`pwd`/../usr
fi
make bootstrap
make install
cd ..
